name: macOS builds
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:  
  macOS_ARM_CI_build:
    #permissions:
    #  contents: write # for actions/checkout to fetch code and softprops/action-gh-release
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6
      - name: Install libraries
        run: |
          brew install autoconf automake nasm glfw glew coreutils sevenzip libslirp fluid-synth pkg-config libtool
          mkdir -p package/dosbox-x
          mkdir -p package/dosbox-x-sdl2
          # cd vs/sdlnet && ./build-dosbox.sh
      - name: Update build info
        run: |
          echo "timestamp=`git show -s --format=%at | xargs -I# gdate -d @# +%Y%m%d%H%M%S`" >> $GITHUB_ENV
          export shortsha=`echo ${GITHUB_SHA} | cut -c1-7`
          export copyrightyear=`git show -s --format=%at | xargs -I# gdate -d @# +'%Y'`
          export updatestr=`git show -s --format=%at | xargs -I# gdate -d @# +'%b %d, %Y %I:%M:%S%P'`
          echo '/* auto generated */' > include/build_timestamp.h
          echo "#define UPDATED_STR \"${updatestr}\"" >> include/build_timestamp.h
          echo "#define GIT_COMMIT_HASH \"${shortsha}\""  >> include/build_timestamp.h
          echo "#define COPYRIGHT_END_YEAR \"${copyrightyear}\"" >> include/build_timestamp.h
          cat include/build_timestamp.h
      - name: Build macOS SDL2
        run: |
          top=`pwd`
          ./build-macos-sdl2
          strip $top/src/dosbox-x
          make dosbox-x.app
          mv dosbox-x.app $top/package/dosbox-x-sdl2
      - name: Package build
        run: |
          top=`pwd`
          cp $top/CHANGELOG $top/package/dosbox-x/CHANGELOG.txt
          cp $top/COPYING $top/package/dosbox-x/COPYING.txt
          cp $top/contrib/macos/readme.txt $top/package/dosbox-x/README.txt
          cp $top/CHANGELOG $top/package/dosbox-x-sdl2/CHANGELOG.txt
          cp $top/COPYING $top/package/dosbox-x-sdl2/COPYING.txt
          cp $top/contrib/macos/readme.txt $top/package/dosbox-x-sdl2/README.txt
          cd $top/package/
          7zz a $top/dosbox-x-macosx-arm64-${{ env.timestamp }}.zip *
          cd $top
      - name: Upload preview package
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dosbox-x-macosx-arm64-${{ env.timestamp }}
          path: ${{ github.workspace }}/dosbox-x-macosx-arm64-${{ env.timestamp }}.zip
